config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "babies#index"

  resources :babies
  resources :breatsfeedings
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baby.rb
class Baby < ApplicationRecord
    
    has_many :breatsfeedings, dependent: :destroy


    def breatsfeeding_count
        self.breatsfeedings.count
        #TODO-implement
    end

    def cantidad_total
        self.breatsfeedings.sum(:cantidad)
        #TODO-implement
    end

    def to_s
        name
    end


    def cuantas_veces
        self.breatsfeedings.where(created_at.to_date == Time.now.to_date).count
    end

    def last_time
        self.breatsfeedings.last.created_at.strftime("%Y-%m-%d")
    end

    def tiempo_hoy
        self.breatsfeedings.where(created_at.to_date == Time.now.to_date).sum(:tiempo)
    end

    def cantidad_hoy
        self.breatsfeedings.where(created_at.to_date == Time.now.to_date).sum(:cantidad)
    end
 
end

app/models/breatsfeeding.rb
class Breatsfeeding < ApplicationRecord
  belongs_to :baby

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_action :set_baby, only: [:show, :edit, :update, :destroy]

  def index
    @babies = Baby.all
  end
      
  def show
    @breatsfeedings = @baby.breatsfeedings
  end

  def new
    @baby = Baby.new
  end

  def edit
  end
    
  def create
    @baby = Baby.new(baby_params)

    respond_to do |format|
      if @baby.save
        format.html { redirect_to @baby, notice: 'Baby was successfully created.' }
        format.json { render :show, status: :created, location: @baby }
      else
        format.html { render :new }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @baby.update(baby_params)
        format.html { redirect_to @baby, notice: 'Baby was successfully updated.' }
        format.json { render :show, status: :ok, location: @baby }
      else
        format.html { render :edit }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @baby.destroy
    respond_to do |format|
      format.html { redirect_to babies_url, notice: 'Baby was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private

  def set_baby
    @baby = Baby.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def baby_params
    params.require(:baby).permit(:name)
  end

end

app/controllers/breatsfeedings_controller.rb
class BreatsfeedingsController < ApplicationController
  before_action :set_breatsfeedings, only: [:show, :edit, :update, :destroy]

  def index
      @breatsfeedings = Breatsfeeding.all
  end


  def show
    @breatsfeeding = Breatsfeeding.find(params[:id])
  end


  def new
    @breatsfeeding = Breatsfeeding.new
    @babies = Baby.all
  end
    
  def edit
    @babies = Baby.all
  end

  
  def create
    @breatsfeeding = Breatsfeeding.new(breatsfeeding_params)
    @babies = Baby.all

    respond_to do |format|
      if @breatsfeeding.save
        format.html { redirect_to @breatsfeeding, notice: 'Breastfeeing was successfully created.' }
        format.json { render :show, status: :created, location: @breatsfeeding }
      else
        format.html { render :new }
        format.json { render json: @breatsfeeding.errors, status: :unprocessable_entity }
      end
    end
  end
  


  def update
    respond_to do |format|
      if @breatsfeeding.update(breatsfeeding_params)
        format.html { redirect_to @breatsfeeding, notice: 'Breastfeeding was successfully updated.' }
        format.json { render :show, status: :ok, location: @breatsfeeding }
      else
        format.html { render :edit }
        format.json { render json: @breatsfeeding.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @breatsfeeding.destroy
    respond_to do |format|
      format.html { redirect_to breatsfeedings_url, notice: 'Breastfeeding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private

  def set_breatsfeedings
    @breatsfeeding = Breatsfeeding.find(params[:id])
  end

  def breatsfeeding_params
    params.require(:breatsfeeding).permit(:cantidad, :tiempo, :baby_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/helpers/breatsfeedings_helper.rb
module BreatsfeedingsHelper
end

app/views/babies/_form.html.erb
<%= form_with(model: baby, local: true) do |form| %>
  <% if baby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(baby.errors.count, "error") %> prohibited this baby from being saved:</h2>

      <ul>
      <% baby.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>Baby</p>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/babies/edit.html.erb
<h1>Editing Baby</h1>

<%= render 'form', baby: @baby %>

<%= link_to 'Show', baby_path(@baby) %> |
<%= link_to 'Back', babies_path %>

app/views/babies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Babies</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Breatsfeedings</th>
      <th>Cantidad Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @babies.each do |baby| %>
      <tr>
        <td><%= baby.name %></td>
        <td><%= baby.breatsfeeding_count %></td>
        <td><%= baby.cantidad_total %></td>
        <td><%= link_to 'Show', baby_path(baby) %></td>
        <td><%= link_to 'Edit', edit_baby_path(baby) %></td>
        <td><%= link_to 'Destroy', baby_path(baby), method: :delete, data: { confirm: 'Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Baby', new_baby_path(@baby) %>

app/views/babies/new.html.erb
<h1>New Baby</h1>

<%= render 'form', baby: @baby %>

<%= link_to 'Back', babies_path(@baby) %>

app/views/babies/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Baby:</strong>
  <%= @baby %>
</p>

<h2>Resumen Hoy</h2>
<table>
  <thead>
    <tr>
      <th>Cuantas veces</th>
      <th>Ultima vez</th>
      <th>Tiempo</th>
      <th>Cantidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @baby.cuantas_veces %></td>
        <td><%= @baby.last_time %></td>
        <td><%= @baby.tiempo_hoy %></td>
        <td><%= @baby.cantidad_hoy %></td>
      </tr>
  </tbody>
</table>

<h2>Historial Breatsfeedings</h2>

<table>
  <thead>
    <tr>
      <th>Cantidad</th>
      <th>Tiempo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <%  @baby.breatsfeedings.each do |breatsfeeding| %>
      <tr>
        <td><%= breatsfeeding.cantidad %></td>
        <td><%= breatsfeeding.tiempo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_baby_path(@baby) %> 
<%= link_to 'Back', root_path %>
<%= link_to 'New Breastfeeding', new_breatsfeeding_path %> 

app/views/breatsfeedings/_form.html.erb
<%= form_with(model: [@baby, breatsfeeding], local: true) do |form| %>
    <% if breatsfeeding.errors.any? %>
    <div id="error_explanation">
        <h2> <%= pluralize(breatsfeeding.errors.count, "error") %> "Impidieron que el breatsfeeding se guarde" </h2>
        
        <ul>
            <% breatsfeeding.errors.full.message.each do |message| %>
                <li> <%= message %></li>
            <% end %> %>
        </ul>
    </div>
    <% end %>

    <div class="field">
        <%= form.label :Cantidad %>
        <%= form.text_field :cantidad %>
    </div>

    <div class="field">
        <%= form.label :Tiempo %>
        <%= form.text_field :tiempo %>
    </div>
    
    <div class="field">
        <%= form.label :Baby %>
        <%= form.select :baby_id, @babies.map{|baby| [baby.name, baby.id] }, prompt: "Seleccione una opción.." %>
    </div>
    
    <div class="actions">
        <%= form.submit %>
    </div>
<% end %> 

app/views/breatsfeedings/edit.html.erb
<h1>Editando Breatsfeeding</h1>

<%= render 'form', breatsfeeding: @breatsfeeding %>

<%= link_to 'Show', baby_breatsfeeding_path(@baby, @breatsfeeding) %>
<%= link_to 'Back', baby_breatsfeedings_path(@baby) %>

app/views/breatsfeedings/index.html.erb
<h1>Breatsfeeding</h1>

<table>
    <thead>
        <tr>
            <th>Cantidad</th>
            <th>Tiempo</th>
            <th>Bebe</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
        <% @breatsfeedings.each do |breatsfeeding| %>
            <tr>
                <td> <%= breatsfeeding.cantidad %> </td>
                <td> <%= breatsfeeding.tiempo %> </td>
                <td> <%= breatsfeeding.baby %> </td>
                <td> <%= link_to 'Show', baby_breatsfeeding_path(@baby, breatsfeeding) %> </td>
                <td><%= link_to 'Edit', edit_baby_breatsfeeding_path(@baby, breatsfeeding) %></td>
                <td><%= link_to 'Destroy', baby_breatsfeeding_path(@baby, breatsfeeding), method: :delete, data: { confirm: 'Seguro?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New breatsfeeding', new_baby_breatsfeeding_path(@baby) %>

app/views/breatsfeedings/new.html.erb
<h1>New breatsfeeding</h1>

<%= render 'form', breatsfeeding: @breatsfeeding  %>

<%= link_to 'Back', breatsfeedings_path %>

app/views/breatsfeedings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cantidad:</strong>
  <%= @breatsfeeding.cantidad %>
</p>

<p>
  <strong>Baby:</strong>
  <%= @breatsfeeding.baby %>
</p>

<%= link_to 'Edit', edit_breatsfeeding_path(@breatsfeeding) %> |
<%= link_to 'Back', babies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bebesapu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render('shared/navbar') %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav>
    <%= link_to 'Babies', root_path %>
</nav>